services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web_server
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app
    command: go run server.go
    
  db:
    image: postgres:13.3
    container_name: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - go_postgres:/var/lib/postgresql/data

volumes:
  go_postgres: